# Note - change these credentials for production use!
# also todo: support loading this via environment variables
s3:
  endpoint: minio:9000
  ssl: false
  access_key: UZgFLiypw2yKUqfm
  secret_key: HaGTqhqSRfjmjrD3patK5HBtJyyUgyMC
mongodb:
  uri: mongodb://admin:abc123def456@localhost:27017
  database: panda_studio