version: "3.9"
services:
  minio:
    image: "quay.io/minio/minio"
    ports: # or expose if we only want docker network access
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=UZgFLiypw2yKUqfm
      - MINIO_ROOT_PASSWORD=HaGTqhqSRfjmjrD3patK5HBtJyyUgyMC
    entrypoint: minio server /data --console-address ":9001"
    volumes:
      - minio:/data
    networks:
      - panda_studio
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123def456
    volumes:
      - mongodb:/data/db
    networks:
      - panda_studio
  
  # Mongo express is
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abc123def456
      - ME_CONFIG_MONGODB_URL=mongodb://admin:abc123def456@mongodb:27017/
    networks:
      - panda_studio
volumes:
  minio:
  mongodb:
networks:
  panda_studio: