ARG GOLANG_VERSION="1.19-bullseye"

FROM golang:${GOLANG_VERSION} as builder

# Install dependencies
# ARG protoc_version="21.12"
ARG go_proto_version="1.28"
ARG go_grpc_version="1.2"

# Install dependencies
RUN apt-get update \
    && apt-get install -y protobuf-compiler
    # && curl -Lo protoc.zip \
    #    "https://github.com/protocolbuffers/protobuf/releases/download/v${protoc_version}/protoc-${protoc_version}-linux-x86_64.zip" \
    # && unzip protoc.zip \

RUN go install "google.golang.org/protobuf/cmd/protoc-gen-go@v${go_proto_version}" \
    && go install "google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${go_grpc_version}"

# Cache the modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

COPY . /app
WORKDIR /app

# Next build it
RUN make panda_executor_test

FROM ubuntu:20.04
WORKDIR /app
COPY --from=builder /app/bin/panda_executor /app/
ENTRYPOINT [ "/app/panda_executor" ]