ARG NODE_VERSION="16-bullseye"

FROM node:${NODE_VERSION}

# Copy frontend
COPY frontend /app/frontend
COPY api /app/api
WORKDIR /app/frontend

# Install dependencies
RUN yarn install

# Build frontend
RUN yarn run generate:api && yarn build

ENTRYPOINT [ "yarn", "start" ]