openapi: '3.0.2'
info:
  title: PANDA Studio API
  version: '0.1'
servers:
  - url: http://localhost:8080/api
paths:
  /images:
    get:
      tags:
        - image
      summary: Finds all Images
      operationId: findAllImages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
  /images/{id}:
    get:
      tags:
        - image
      summary: Get image with specified ID
      operationId: findImageById
      parameters:
        - name: id
          in: path
          description: ID of image to find
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '404':
          description: Not Found
components:
  schemas:
    Image:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/ImageFile'
        config:
          $ref: '#/components/schemas/ImageConfiguration'

    ImageFile:
      type: object
      properties:
        id:
          type: string
        file_name:
          type: string
        file_type:
          type: string
        sha256:
          type: string

    ImageConfiguration:
      type: object