openapi: "3.0.2"
info:
  title: PANDA Studio API
  version: "0.1"
servers:
  - url: http://localhost:8080/api
    description: Development server
paths:
  # todo: create image, delete image, update image
  /images:
    get:
      tags:
        - image
      summary: Finds all Images
      operationId: findAllImages
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"
    post:
      tags:
        - image
      summary: Creates new Image
      operationId: createImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateImageRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
  /images/{imageId}:
    get:
      tags:
        - image
      summary: Get image with specified ID
      operationId: findImageById
      parameters:
        - $ref: "#/components/parameters/ImageId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    put:
      tags:
        - image
      summary: Update image
      operationId: updateImage
      parameters:
        - $ref: "#/components/parameters/ImageId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    delete:
      tags:
        - image
      summary: Delete image with specified ID
      operationId: deleteImageById
      parameters:
        - $ref: "#/components/parameters/ImageId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
  /images/{imageId}/files:
    post:
      tags:
        - image
        - file
      summary: Create new image file
      operationId: createImageFile
      parameters:
        - $ref: "#/components/parameters/ImageId"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateImageFileRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageFile"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
        "409":
          $ref: "#/components/responses/ConflictResponse"
  /images/{imageId}/files/{fileId}:
    get:
      tags:
        - image
        - file
      summary: Download image file
      operationId: downloadImageFile
      parameters:
        - $ref: "#/components/parameters/ImageId"
        - $ref: "#/components/parameters/FileId"
      responses:
        "200":
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    delete:
      tags:
        - image
        - file
      summary: Delete image file
      operationId: deleteImageFile
      parameters:
        - $ref: "#/components/parameters/ImageId"
        - $ref: "#/components/parameters/FileId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageFile"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
  /recordings:
    get:
      tags:
        - recording
      summary: Finds all Recordings
      operationId: findAllRecordings
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recording"
    post:
      tags:
        - recording
      summary: Creates new Recording
      operationId: createRecording
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRecordingRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recording"
  /recordings/{recordingId}:
    get:
      tags:
        - recording
      summary: Get recording with specified ID
      operationId: findRecordingById
      parameters:
        - $ref: "#/components/parameters/RecordingId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recording"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
    delete:
      tags:
        - recording
      summary: Delete recording with specified ID
      operationId: deleteRecordingById
      parameters:
        - $ref: "#/components/parameters/RecordingId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recording"
        "404":
          $ref: "#/components/responses/NotFoundResponse"
components:
  parameters:
    ImageId:
      name: imageId
      in: path
      description: ID of image
      required: true
      schema:
        type: string
    FileId:
      name: fileId
      in: path
      description: ID of file
      required: true
      schema:
        type: string
    RecordingId:
      name: recordingId
      in: path
      description: ID of recording
      required: true
      schema:
        type: string
  responses:
    NotFoundResponse:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ConflictResponse:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
            details:
              type: string
    Image:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        files:
          type: array
          items:
            $ref: "#/components/schemas/ImageFile"
        config:
          $ref: "#/components/schemas/PandaConfig"

    ImageFile:
      type: object
      properties:
        id:
          type: string
        file_name:
          type: string
        file_type:
          $ref: "#/components/schemas/ImageFileType"
        size:
          type: integer
        sha256:
          type: string
    
    ImageFileType:
      type: string
      enum: [qcow2, dtb, kernel]

    RecordingFileType:
      type: string
      enum: [ snp, ndlog ]

    PandaConfig:
      # todo: define this schema
      type: object
    
    CreateImageRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        config:
          $ref: "#/components/schemas/PandaConfig"

    CreateImageFileRequest:
      type: object
      properties:
        file_name:
          type: string
        file_type:
          $ref: "#/components/schemas/ImageFileType"
        file:
          type: string
          format: binary
    
    Recording:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        imageId:
          type: string
        recordingFiles:
          type: array
          items:
            $ref: "#/components/schemas/RecordingFile"

    RecordingFile:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        file_type:
          $ref: "#/components/schemas/RecordingFileType"
        size:
          type: integer
        sha256:
          type: string

    CreateRecordingRequest:
      type: object
      properties:
        name:
          type: string
        imageId:
          type: string
        interactionId:
          type: string
        config:
          $ref: "#/components/schemas/PandaConfig"

    CreateRecordingFileRequest:
      type: object
      properties:
        name:
          type: string
        recordingId:
          type: string
        file:
          type: string
          format: binary

    InteractionProgram:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        instructions:
          type: array
          items:
            $ref: "#/components/schemas/InteractionProgramInstruction"
    
    InteractionProgramInstruction:
      oneOf:
        - $ref: "#/components/schemas/RunCommandInstruction"
        - $ref: "#/components/schemas/StartRecordingInstruction"
        - $ref: "#/components/schemas/StopRecordingInstruction"
      discriminator:
        propertyName: "type"
        mapping:
          command: "#/components/schemas/RunCommandInstruction"
          start_recording: "#/components/schemas/StartRecordingInstruction"
          stop_recording: "#/components/schemas/StopRecordingInstruction"
    
    RunCommandInstruction:
      type: object
      required:
        - type
        - command
      properties:
        type:
          type: string
        command:
          type: string
    
    StartRecordingInstruction:
      type: object
      required:
        - type
        - recording_name
      properties:
        type:
          type: string
        recording_name:
          type: string
    
    StopRecordingInstruction:
      type: object
      required:
        - type
      properties:
        type:
          type: string