name: Build PANDA Studio
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_agent :
    runs-on: ubuntu-20.04
    name: Build PANDA Agent Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA Agent Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-agent
           -t pandare/panda_agent
           ./panda_agent

  build_executor:
    runs-on: ubuntu-20.04
    name: Build PANDA Executor Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA Executor Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-executor
           -t pandare/panda_executor
           .

  build_api:
    runs-on: ubuntu-20.04
    name: Build PANDA API Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA API Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-api
           -t pandare/panda_api
           .

  build_frontend:
    runs-on: ubuntu-20.04
    name: Build React Frontend
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install yarn
      run: npm install -g yarn
    - name: Install npm packages using yarn
      run: yarn install
    - name: Generate API client
      run: yarn run generate:api
    - name: Build static site
      run: yarn run build