name: Build Panda Agent Docker Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout PANDA Studio at current commit
      uses: actions/checkout@v2
    - name: Build PANDA Agent Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-agent
           -t pandare/panda_agent
           ./panda_agent
    - name: Build PANDA Executor Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-executor
           -t pandare/panda_executor
           .