name: Build PANDA Studio
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_agent :
    runs-on: ubuntu-20.04
    name: Build PANDA Agent Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA Agent Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-agent
           -t pandare/panda_agent
           ./panda_agent

  build_api:
    runs-on: ubuntu-20.04
    name: Build PANDA API Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA API Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-api
           -t pandare/panda_api
           .

  build_frontend:
    runs-on: ubuntu-20.04
    name: Build React Frontend
    steps:
    - uses: actions/checkout@v3
    - name: Build React Frontend Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.frontend
           -t pandare/panda_api
           .