name: Build Panda Agent Docker Container
on: [push]
jobs:
  build_agent :
    runs-on: ubuntu-20.04
    name: Build PANDA Agent Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA Agent Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-agent
           -t pandare/panda_agent
           ./panda_agent

  build_executor:
    runs-on: ubuntu-20.04
    name: Build PANDA Executor Container
    steps:
    - uses: actions/checkout@v3
    - name: Build PANDA Executor Container
      run: DOCKER_BUILDKIT=1 docker build
           --progress=plain
           -f ./docker/Dockerfile.panda-executor
           -t pandare/panda_executor
           .

  build_frontend:
    runs-on: ubuntu-20.04
    name: Build React Frontend
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install yarn
      run: npm install -g yarn
    - name: Install npm packages using yarn
      run: yarn install
    - name: Build static site
      run: yarn run build